language: node_js
node_js:
  - "8"
# https://github.com/greenkeeperio/greenkeeper-lockfile/issues/98
before_install:
  - export PATH=$PATH:`yarn global bin`
  - yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
